name: Make Plug-ins Archive

on:
  push:
    tags:
      - 'v*'  # Runs action on pushed tags starting with 'v'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GNU Arm Embedded Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi

      - name: Install Faust
        run: |
          sudo apt-get install -y faust

      - name: Verify installation
        run: |
          arm-none-eabi-g++ --version
          faust --version

      - name: Run make in directories
        run: |
          DIRECTORIES=("examples" "faust/examples")  # Replace with your actual directories
          for DIR in "${DIRECTORIES[@]}"; do
            echo "Building in $DIR"
            (cd "$DIR" && make clean && make)
          done

      - name: Collect and zip object files
        run: |
          mkdir -p programs/plug-ins
          find . -type f -name "*.o" -exec cp --parents {} programs/plug-ins/ \;
          zip -r plug-ins.zip programs/plug-ins/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: plug-ins.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
